Expro/Areas/User/Controllers/UserChangePasswordController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Expro.Controllers;
using Expro.Models;
using Expro.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Expro.Areas.User.Controllers
{
    [Area("User")]
    public class UserChangePasswordController : BaseController
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public UserChangePasswordController(
             UserManager<ApplicationUser> userManager,
             SignInManager<ApplicationUser> signInManager
             )
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            ViewBag.Message = false;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(PasswordChangeVM vmodel)
        {
            ViewBag.Message = false;
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                if (user == null)
                {
                    return RedirectToAction("Login");
                }

                // ChangePasswordAsync changes the user password
                var result = await _userManager.ChangePasswordAsync(user, vmodel.Password, vmodel.NewPassword);

                if (!result.Succeeded)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                    return View(vmodel);
                }

                // Upon successfully changing the password refresh sign-in cookie
                await _signInManager.RefreshSignInAsync(user);
                ViewBag.Message = true;
                return View();
            }

            // If we got this far, something failed, redisplay form
            return View(vmodel);
        }
    }
}

Expro/Areas/User/Views/UserChangePassword/Index.cshtml
@model Expro.ViewModels.PasswordChangeVM
@{
    ViewData["Title"] = localizer["ChangePassword"];
}

<h4>@ViewData["Title"]</h4>

<form asp-controller="UserChangePassword" asp-action="Index" data-ajax="true" data-ajax-method="POST">
    @if ((bool)ViewBag.Message)
    {
    <div class="alert alert-soft-success" role="alert">
        @localizer["ChangesSaved"]
    </div>
    }
    <div asp-validation-summary="All" class="text-danger"></div>

    <!-- Form Group -->
    <div class="js-form-message form-group">
        <label class="input-label" asp-for="@Model.Password"></label>
        <input class="form-control" asp-for="@Model.Password" placeholder="******" aria-label="" required
               data-msg="Please fill field.">
        <span asp-validation-for="@Model.Password"></span>
    </div>
    <!-- End Form Group -->
    <!-- Form Group -->
    <div class="js-form-message form-group">
        <label class="input-label" asp-for="@Model.NewPassword"></label>
        <input class="form-control" asp-for="@Model.NewPassword" placeholder="******" aria-label="" required
               data-msg="Please fill field.">
        <span asp-validation-for="@Model.NewPassword"></span>
    </div>
    <!-- End Form Group -->
    <!-- Form Group -->
    <div class="js-form-message form-group">
        <label class="input-label" asp-for="@Model.ConfirmPassword"></label>
        <input class="form-control" asp-for="@Model.ConfirmPassword" placeholder="******" aria-label="" required
               data-msg="Please fill field.">
        <span asp-validation-for="@Model.ConfirmPassword"></span>
    </div>
    <!-- End Form Group -->
    <!-- Button -->
    <div class="row align-items-center mb-5">
        <div class="col-sm-12 text-sm-center">
            <button type="submit" class="btn btn-primary transition-3d-hover">@localizer["SaveButton"]</button>
        </div>
    </div>
    <!-- End Button -->
</form>