Expro/Areas/Admin/Controllers/VacancyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Expro.Controllers;
using Expro.Models;
using Expro.Models.Enums;
using Expro.Services.Interfaces;
using Expro.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Expro.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class VacancyController : BaseController
    {  
        private readonly IVacancyStatusService _vacancyStatusService;
        private readonly IVacancySearchService _vacancySearchService;
        private readonly IVacancyService _vacancyService;
        private readonly IVacancyAdminActionsService _vacancyAdminActionsService;

        public VacancyController(
             IVacancySearchService vacancySearchService,
             IVacancyService vacancyService,
             IVacancyStatusService vacancyStatusService,
             IVacancyAdminActionsService vacancyAdminActionsService)
        {
            _vacancyStatusService = vacancyStatusService;
            _vacancySearchService = vacancySearchService;
            _vacancyService = vacancyService;
            _vacancyAdminActionsService = vacancyAdminActionsService;
        }

        public IActionResult Index()
        {
            ViewData["statuses"] = _vacancyStatusService.GetAsSelectList();
            return View();
        }

        [HttpPost]
        public IActionResult Search(int draw, int? start = null, int? length = null,  int? statusID = null)
        {
            int recordsTotal = 0;
            int recordsFiltered = 0;
            string error = "";

            IQueryable<Vacancy> dataIQueryable = _vacancySearchService.Search(
                start,
                length,

                out recordsTotal,
                out recordsFiltered,
                out error,

                UserTypesEnum.Admin,
                statusID,
                null,
                null,
                null
            );

            dynamic data = new VacancyDetailsVM().GetListOfVacancyDetailsVM(dataIQueryable);

            return Json(new
            {
                draw = draw,
                recordsTotal = recordsTotal,
                recordsFiltered = recordsFiltered,
                data = data,
                error = error
            });
        }


        public IActionResult Details(int id)
        {
            var vacancy = _vacancyService.GetByID(id);
            if (vacancy == null)
                throw new Exception("Вакансия не найдена");

            VacancyDetailsVM vacancyDetailsVM = new VacancyDetailsVM(vacancy);

            return View(vacancyDetailsVM);
        }

        [HttpPost]
        public IActionResult Approve(int id)
        {
            try
            {
                var vacancy = _vacancyService.GetByID(id);
                if (vacancy == null)
                    throw new Exception("Вакансия не найдена");

                var curUser = accountUtil.GetCurrentUser(User);
                _vacancyAdminActionsService.Approve(vacancy, curUser.ID);
                return Ok();
            }
            catch (Exception ex)
            {
                return CustomBadRequest(ex);
            }
        }

        [HttpPost]
        public IActionResult Reject(int id)
        {
            try
            {
                var vacancy = _vacancyService.GetByID(id);
                if (vacancy == null)
                    throw new Exception("Вакансия не найдена");

                var curUser = accountUtil.GetCurrentUser(User);
                _vacancyAdminActionsService.Reject(vacancy, curUser.ID);
                return Ok();
            }
            catch (Exception ex)
            {
                return CustomBadRequest(ex);
            }
        }
    }
}

Expro/Areas/Expert/Controllers/VacancyController.cs
using System;
using System.Collections.Generic;
using Expro.Controllers;
using Expro.Models;
using Expro.Models.Enums;
using Expro.Services.Interfaces;
using Expro.Utils;
using Expro.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Expro.Areas.Expert.Controllers
{
    [Area("Expert")]
    public class VacancyController : BaseController
    {
        private readonly IVacancyService _vacancyService;
        private readonly ILawAreaService _lawAreaService;
        private readonly IRegionService _regionService;
        private readonly ICityService _cityService;

        public VacancyController(
              IVacancyService vacancyService,
              ILawAreaService lawAreaService,
              IRegionService regionService,
              ICityService cityService
              )
        {           
            _vacancyService = vacancyService;
            _lawAreaService = lawAreaService;
            _regionService = regionService;
            _cityService = cityService;
        }

        public IActionResult Index(bool? successfullyCreated = null)
        {
            ViewData["successfullyCreated"] = successfullyCreated;

            var user = accountUtil.GetCurrentUser(User);

            var vacancies = _vacancyService.GetVacancyByCreatorID(user.ID);

            return View(new VacancyDetailsVM().GetListOfVacancyDetailsVM(vacancies));
        }

        public IActionResult Create()
        {
            GetVacancyViewDataForCreate();
            return View();
        }

        [HttpPost]
        public IActionResult Create(VacancyEditVM vmodel)
        {
            try
            {
                var user = accountUtil.GetCurrentUser(User);
                //GetVacancyViewDataForCreate();
                if (ModelState.IsValid && user != null)
                {
                    Vacancy model = new Vacancy();
                    model.VacancyStatusID = (int)VacancyStatusEnum.WaitingForApproval;
                    PropertyCopier.CopyTo(vmodel, model);

                    _vacancyService.Add(model, user.ID);

                    if (vmodel.ActionType == DocumentActionTypesEnum.submitForApproval)
                        _vacancyService.SubmitForApproval(model, user.ID);

                    //return RedirectToAction("Index");
                    return Ok(new { id = model.ID });
                }
                else
                    //throw new Exception("Неверные данные");
                    return BadRequest(ModelState);
            }
            catch (Exception ex)
            {
                return CustomBadRequest(ex);
            }
        }

        public void GetVacancyViewDataForCreate()
        {
            ViewData["regions"] = _regionService.GetAsSelectList();
            ViewData["cities"] = _cityService.GetAsSelectList();
        }


        public IActionResult Edit(int id, bool? successfullySaved = null)
        {
            var user = accountUtil.GetCurrentUser(User);
            if (!_vacancyService.VacancyBelongsToUser(id, user.ID))
            {
                throw new Exception("Редактирование невозможно");
            }

            VacancyEditVM vmodel = new VacancyEditVM(_vacancyService.GetByID(id));
            GetVacancyViewDataForEdit(vmodel);

            ViewData["successfullySaved"] = successfullySaved;

            return View(vmodel);
        }

        [HttpPost]
        public IActionResult Edit(VacancyEditVM vmodel)
        {
            try
            {
                var user = accountUtil.GetCurrentUser(User);

                if (!_vacancyService.VacancyBelongsToUser(vmodel.ID, user.ID))
                {
                    throw new Exception("Редактирование невозможно");
                }

                //GetVacancyViewDataForEdit(vmodel);
            
                if (ModelState.IsValid && user != null)
                {
                    Vacancy model = _vacancyService.GetActiveByID(vmodel.ID);
                    model.VacancyStatusID = (int)VacancyStatusEnum.WaitingForApproval;
                    PropertyCopier.CopyTo(vmodel, model);

                    if (vmodel.ActionType == DocumentActionTypesEnum.submitForApproval)
                    {
                        _vacancyService.SubmitForApproval(model, user.ID);

                        //vmodel.StatusID = (int)DocumentStatusesEnum.WaitingForApproval;
                    }
                    else
                        _vacancyService.Update(model, user.ID);

                    return Ok();
                }
                else
                    //throw new Exception("Неверные данные");
                    return BadRequest(ModelState);
            }
            catch (Exception ex)
            {
                return CustomBadRequest(ex);
            }
        }

        public void GetVacancyViewDataForEdit(VacancyEditVM vmodel)
        {
            ViewData["regions"] = _regionService.GetAsSelectListOne(vmodel.RegionID);
            ViewData["cities"] = _cityService.GetAsSelectListOne(vmodel.CityID);
        }

        //public ActionResult Details(int id)
        //{
        //    VacancyDetailsVM vmodel = new VacancyDetailsVM(_vacancyService.GetByID(id));
        //    return View(vmodel);
        //}

        //public ActionResult Delete(int id)
        //{
        //    VacancyDetailsVM vmodel = new VacancyDetailsVM(_vacancyService.GetByID(id));
        //    return View(vmodel);
        //}

        //[HttpPost]
        //public IActionResult Delete(VacancyDetailsVM vmodel)
        //{
        //    try
        //    {
        //        var model = _vacancyService.GetByID(vmodel.ID);
        //        var user = accountUtil.GetCurrentUser(User);
        //        if (_vacancyService.VacancyBelongsToUser(model, user.ID))
        //        {
        //            _vacancyService.DeletePermanently(model);
        //            return RedirectToAction("Index");
        //        }
        //        throw new Exception("Что то пошло не так. Вакансия не удалена");
        //    }
        //    catch (Exception ex)
        //    {
        //        throw new Exception("Что то пошло не так. Вакансия не удалена");
        //    }
        //}      
    }
}

Expro/Areas/User/Controllers/VacancyController.cs
using System;
using System.Collections.Generic;
using Expro.Controllers;
using Expro.Models;
using Expro.Models.Enums;
using Expro.Services.Interfaces;
using Expro.Utils;
using Expro.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Expro.Areas.User.Controllers
{
    [Area("User")]
    public class VacancyController : BaseController
    {
        private readonly IVacancyService _vacancyService;
        private readonly ILawAreaService _lawAreaService;
        private readonly IRegionService _regionService;
        private readonly ICityService _cityService;

        public VacancyController(
              IVacancyService vacancyService,
              ILawAreaService lawAreaService,
              IRegionService regionService,
              ICityService cityService
              )
        {
            _vacancyService = vacancyService;
            _lawAreaService = lawAreaService;
            _regionService = regionService;
            _cityService = cityService;
        }

        public IActionResult Index(bool? successfullyCreated = null)
        {
            ViewData["successfullyCreated"] = successfullyCreated;

            var user = accountUtil.GetCurrentUser(User);

            var vacancies = _vacancyService.GetVacancyByCreatorID(user.ID);

            return View(new VacancyDetailsVM().GetListOfVacancyDetailsVM(vacancies));
        }

        public IActionResult Create()
        {
            GetVacancyViewDataForCreate();
            return View();
        }

        [HttpPost]
        public IActionResult Create(VacancyEditVM vmodel)
        {
            try
            {
                var user = accountUtil.GetCurrentUser(User);
                //GetVacancyViewDataForCreate();
                if (ModelState.IsValid && user != null)
                {
                    Vacancy model = new Vacancy();
                    model.VacancyStatusID = (int)VacancyStatusEnum.WaitingForApproval;
                    PropertyCopier.CopyTo(vmodel, model);

                    _vacancyService.Add(model, user.ID);

                    if (vmodel.ActionType == DocumentActionTypesEnum.submitForApproval)
                        _vacancyService.SubmitForApproval(model, user.ID);

                    //return RedirectToAction("Index");
                    return Ok(new { id = model.ID });
                }
                else
                    //throw new Exception("Неверные данные");
                    return BadRequest(ModelState);
            }
            catch (Exception ex)
            {
                return CustomBadRequest(ex);
            }
        }

        public void GetVacancyViewDataForCreate()
        {
            ViewData["regions"] = _regionService.GetAsSelectList();
            ViewData["cities"] = _cityService.GetAsSelectList();
        }


        public IActionResult Edit(int id, bool? successfullySaved = null)
        {
            var user = accountUtil.GetCurrentUser(User);
            if (!_vacancyService.VacancyBelongsToUser(id, user.ID))
            {
                throw new Exception("Редактирование невозможно");
            }

            VacancyEditVM vmodel = new VacancyEditVM(_vacancyService.GetByID(id));
            GetVacancyViewDataForEdit(vmodel);

            ViewData["successfullySaved"] = successfullySaved;

            return View(vmodel);
        }

        [HttpPost]
        public IActionResult Edit(VacancyEditVM vmodel)
        {
            try
            {
                var user = accountUtil.GetCurrentUser(User);

                if (!_vacancyService.VacancyBelongsToUser(vmodel.ID, user.ID))
                {
                    throw new Exception("Редактирование невозможно");
                }

                //GetVacancyViewDataForEdit(vmodel);

                if (ModelState.IsValid && user != null)
                {
                    Vacancy model = _vacancyService.GetActiveByID(vmodel.ID);
                    model.VacancyStatusID = (int)VacancyStatusEnum.WaitingForApproval;
                    PropertyCopier.CopyTo(vmodel, model);

                    if (vmodel.ActionType == DocumentActionTypesEnum.submitForApproval)
                    {
                        _vacancyService.SubmitForApproval(model, user.ID);

                        //vmodel.StatusID = (int)DocumentStatusesEnum.WaitingForApproval;
                    }
                    else
                        _vacancyService.Update(model, user.ID);

                    return Ok();
                }
                else
                    //throw new Exception("Неверные данные");
                    return BadRequest(ModelState);
            }
            catch (Exception ex)
            {
                return CustomBadRequest(ex);
            }
        }

        public void GetVacancyViewDataForEdit(VacancyEditVM vmodel)
        {
            ViewData["regions"] = _regionService.GetAsSelectListOne(vmodel.RegionID);
            ViewData["cities"] = _cityService.GetAsSelectListOne(vmodel.CityID);
        }

        //public ActionResult Details(int id)
        //{
        //    VacancyDetailsVM vmodel = new VacancyDetailsVM(_vacancyService.GetByID(id));
        //    return View(vmodel);
        //}

        //public ActionResult Delete(int id)
        //{
        //    VacancyDetailsVM vmodel = new VacancyDetailsVM(_vacancyService.GetByID(id));
        //    return View(vmodel);
        //}

        //[HttpPost]
        //public IActionResult Delete(VacancyDetailsVM vmodel)
        //{
        //    try
        //    {
        //        var model = _vacancyService.GetByID(vmodel.ID);
        //        var user = accountUtil.GetCurrentUser(User);
        //        if (_vacancyService.VacancyBelongsToUser(model, user.ID))
        //        {
        //            _vacancyService.DeletePermanently(model);
        //            return RedirectToAction("Index");
        //        }
        //        throw new Exception("Что то пошло не так. Вакансия не удалена");
        //    }
        //    catch (Exception ex)
        //    {
        //        throw new Exception("Что то пошло не так. Вакансия не удалена");
        //    }
        //}      
    }
}

Expro/Areas/Expert/Views/Vacancy/Delete.cshtml
@*@model VacancyDetailsVM
@using Expro.ViewModels
@{
    ViewData["Title"] = "Удаление вакансии";
}


<h4>Вы действительно хотите удалить вакансию?</h4>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Company"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Company)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Region"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Region)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.City"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.City)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.CityOther"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.CityOther)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Position"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Position)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Responsibility"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Responsibility)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Requirements"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Requirements)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Salary"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Salary)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Contacts"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Contacts)
        </p>
    </div>
</div>


<form asp-action="Delete">
    <input type="hidden" asp-for="@Model.ID" class="form-control" />
    <input type="submit" value="Удалить" class="btn btn-danger" />
</form>

<div class="row">
    <a asp-action="Index">Вернутся к списку</a>
</div>*@

Expro/Areas/Expert/Views/Vacancy/Details.cshtml
@*@model VacancyDetailsVM
@using Expro.ViewModels
@{
    ViewData["Title"] = "Просмотр вакансии";
}

<h4>Просмотр вакансии</h4>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Company"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Company)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Region"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Region)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.City"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.City)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.CityOther"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.CityOther)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Position"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Position)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Responsibility"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Responsibility)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Requirements"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Requirements)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Salary"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Salary)
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <label asp-for="@Model.Contacts"></label>
    </div>
    <div class="col-md-9">
        <p>
            @Html.DisplayFor(m => m.Contacts)
        </p>
    </div>
</div>

<div>
    <a asp-action="Index">Вернутся к списку</a>
</div>*@

Expro/Areas/Expert/Views/Vacancy/Index.cshtml
@model IEnumerable<Expro.ViewModels.VacancyDetailsVM>
@using Expro.ViewModels
@using Expro.Models.Enums

@{
    ViewData["Title"] = localizer["Vacancies"];
    @*<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">*@
}

<h2>@ViewData["Title"]</h2>
<hr />

@if (ViewData["successfullyCreated"] != null)
{
<div class="alert alert-soft-success text-center rounded-0 mb-0" role="alert">
    @localizer["VacancyAdded"]  
</div>
    <br />
}

<div class="row">
    <div class="col-md-12">
        @Html.ActionLink(localizer["AddVacation"], "Create", "Vacancy", null, new { @class = "btn btn-primary" })
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <br />
        <table id="list" width="100%">
            <thead>
                <tr>                  
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>                      
                        <td>
                            <div class="card card-bordered card-hover-shadow mb-5">
                                <div class="card-body">
                                    <div class="d-sm-flex">
                                        <div class="media-body">
                                            <div class="row">
                                                <div class="col col-md-8">
                                                    <h3 class="mb-0">
                                                        <a class="text-dark" href="/Expert/Vacancy/Edit/@item.ID" target="_blank">@item.Position</a>
                                                    </h3>
                                                    <div class="d-none d-sm-block">
                                                        @item.Company
                                                    </div>
                                                </div>
                                                <div class="col-12 col-md mt-3 mt-md-2">
                                                    <span class="d-block font-size-1 text-body mb-1">@item.Salary</span>

                                                    @{
                                                        string badgeClass = "";
                                                        if (item.Status.ID == ((int)VacancyStatusEnum.NotApproved))
                                                        {
                                                            badgeClass = "info";
                                                        }
                                                        else if (item.Status.ID == ((int)VacancyStatusEnum.WaitingForApproval))
                                                        {
                                                            badgeClass = "warning";
                                                        }
                                                        else if (item.Status.ID == ((int)VacancyStatusEnum.Approved))
                                                        {
                                                            badgeClass = "success";
                                                        }
                                                        else if (item.Status.ID == ((int)VacancyStatusEnum.Rejected))
                                                        {
                                                            badgeClass = "danger";
                                                        }
                                                    }
                                                    <span class="badge badge-soft-@badgeClass mr-2">
                                                        <span class="legend-indicator bg-@badgeClass"></span>@item.Status.Name
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <ul class="list-inline list-separator small text-body">
                                        <li class="list-inline-item"><i class="fa fa-location-arrow"></i> @item.Region.Name, @item.City.Name</li>
                                        @if (!string.IsNullOrWhiteSpace(item.PhoneNumber))
                                        {
                                            <li class="list-inline-item"><i class="fa fa-phone"></i> @item.PhoneNumber</li>
                                        }
                                        @if (!string.IsNullOrWhiteSpace(item.Email))
                                        {
                                            <li class="list-inline-item"><i class="fa fa-envelope"></i> @item.Email</li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<link href="~/lib/DataTables-1.10.22/datatables.css" rel="stylesheet" />

@section Scripts{
    <script src="~/lib/DataTables-1.10.22/datatables.js"></script>
    <script>
        $(document).ready(function () {
            $("table#list").DataTable({
                searching: false,
                ordering: false,
                lengthChange: false,
                scrollX: true,
                lengthChange: false,
                language: InitDataTableLanguage(),
            });
        });
    </script>
}